const CURRENT_LOCATION_UPDATED = "CURRENT_LOCATION_UPDATED";
const SELECTED_LOCATION_UPDATED = "SELECTED_LOCATION_UPDATED";
const LOCATION_UPDATED = "LOCATION_UPDATED";
export { CURRENT_LOCATION_UPDATED, SELECTED_LOCATION_UPDATED ,LOCATION_UPDATED};
